use_frameworks!

platform :ios, '8.0'

target 'SFCommonKit_Example' do
  pod 'SFCommonKit', :path => '../'

  target 'SFCommonKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
